name: Build & Run tests & Publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 11.x
        uses: actions/setup-node@master
        with:
          node-version: 11.x

      - name: Install dependencies # Install all deps
        run: yarn

      - name: Build Mapycz # Build
        run: yarn build

      - name: Publish to npm # Publish to npm
        uses: actions/npm@master
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          args: publish --folder dist/mapycz
